services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
   # image: mowoli:2.0
    ports:
      - "80:3000"
    volumes:
      - .:/opt/mowoli
      - db:/opt/mowoli/var/db
      - hl7:/opt/mowoli/var/hl7
      - mwl:/opt/mowoli/var/mwl
  dicom:
    image: bjoernalbers/dcm4che2
    ports:
      - "11112:11112"
    volumes:
      - mwl:/opt/dcm4che2/var
    command:
      - "dcmof"
      - "-mwl"
      - "var"
      - "11112"
volumes:
  db:
  hl7:
  mwl:
